# Generated by Django 5.2.8 on 2025-11-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField(choices=[('L', 'Luneta'), ('I', 'Intramuros'), ('B', 'Binondo')])),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('type', models.TextField(choices=[('C', 'Classroom'), ('L', 'Laboratory'), ('G', 'Gymnasium')])),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.IntegerField(choices=[(0, 'Recess'), (1, 'Lunch Break'), (2, 'Science'), (3, 'Filipino'), (4, 'English'), (5, 'Mathematics'), (6, 'Araling Panlipunan'), (7, 'Edukasyon sa Pagpapakatao'), (8, 'Technology and Livelihood Education'), (9, 'MAPEH'), (10, 'ICT')])),
                ('grade_level', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('sessions_per_week', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('max_weekly_hours', models.IntegerField(default=30)),
                ('subject_taught', models.IntegerField(choices=[(0, 'Recess'), (1, 'Lunch Break'), (2, 'Science'), (3, 'Filipino'), (4, 'English'), (5, 'Mathematics'), (6, 'Araling Panlipunan'), (7, 'Edukasyon sa Pagpapakatao'), (8, 'Technology and Livelihood Education'), (9, 'MAPEH'), (10, 'ICT')])),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='teacheravailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.teacher')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Schedule Entries',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'timeslot'), name='unique_teacher_slot'), models.UniqueConstraint(fields=('room', 'timeslot'), name='unique_room_slot'), models.UniqueConstraint(fields=('section', 'timeslot'), name='unique_section_slot')],
            },
        ),
    ]
