# Generated by Django 5.2.8 on 2025-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.AddField(
            model_name='section',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='class_scheduler_app.subject'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=30, editable=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='grade_level',
            field=models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='duration_minutes',
            field=models.IntegerField(default=60, editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sessions_per_week',
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.IntegerField(choices=[(3, 'Filipino'), (4, 'English'), (5, 'Mathematics'), (6, 'Araling Panlipunan'), (7, 'Edukasyon sa Pagpapakatao'), (8, 'Technology and Livelihood Education'), (9, 'MAPEH'), (10, 'Homeroom Guidance Program')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_taught',
            field=models.IntegerField(choices=[(3, 'Filipino'), (4, 'English'), (5, 'Mathematics'), (6, 'Araling Panlipunan'), (7, 'Edukasyon sa Pagpapakatao'), (8, 'Technology and Livelihood Education'), (9, 'MAPEH'), (10, 'Homeroom Guidance Program')]),
        ),
        migrations.DeleteModel(
            name='scheduleentry',
        ),
        migrations.DeleteModel(
            name='timeslot',
        ),
    ]
