# Generated by Django 5.2.8 on 2025-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0002_remove_room_building_section_subjects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
