# Generated by Django 5.2.8 on 2025-11-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0003_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
    ]
