# Generated by Django 5.2.8 on 2025-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0004_remove_subject_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.IntegerField(choices=[(1, 'Science'), (2, 'Filipino'), (3, 'English'), (4, 'Mathematics'), (5, 'Araling Panlipunan'), (6, 'Edukasyon sa Pagpapakatao'), (7, 'Technology and Livelihood Education'), (8, 'MAPEH'), (9, 'Homeroom Guidance Program')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_taught',
            field=models.IntegerField(choices=[(1, 'Science'), (2, 'Filipino'), (3, 'English'), (4, 'Mathematics'), (5, 'Araling Panlipunan'), (6, 'Edukasyon sa Pagpapakatao'), (7, 'Technology and Livelihood Education'), (8, 'MAPEH'), (9, 'Homeroom Guidance Program')]),
        ),
        migrations.DeleteModel(
            name='teacheravailability',
        ),
    ]
