# Generated by Django 5.2.8 on 2025-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0005_alter_subject_subject_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='max_weekly_hours',
        ),
        migrations.AddField(
            model_name='teacher',
            name='periods_per_week',
            field=models.IntegerField(default=10, editable=False),
        ),
    ]
