# Generated by Django 5.2.8 on 2025-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0006_remove_teacher_max_weekly_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='periods_per_week',
        ),
        migrations.AddField(
            model_name='teacher',
            name='availability',
            field=models.TextField(choices=[('U', 'Unavailable'), ('M', 'Available Morning Weekly'), ('A', 'Available Afternoon Weekly')], default='U'),
        ),
    ]
