# Generated by Django 5.2.8 on 2025-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0007_remove_teacher_periods_per_week_teacher_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.TextField(choices=[('Unavailable', 'Unavailable'), ('Available Morning Weekly', 'Available Morning Weekly'), ('Available Afternoon Weekly', 'Available Afternoon Weekly'), ('Available Whole Day Weekly', 'Available Whole Day Weekly')], default='Unavailable'),
        ),
    ]
