# Generated by Django 5.2.8 on 2025-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0008_alter_teacher_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
        migrations.AddField(
            model_name='section',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.TextField(choices=[('Classroom', 'Classroom'), ('Laboratory', 'Laboratory')], default='Classroom'),
        ),
    ]
