# Generated by Django 5.2.8 on 2025-11-27 15:38

import class_scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0009_delete_room_section_availability_section_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='availability',
            field=models.JSONField(blank=True, default=class_scheduler_app.models.default_availability),
        ),
    ]
