# Generated by Django 5.2.8 on 2025-11-27 15:58

import class_scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0010_alter_section_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sessions_per_week',
        ),
        migrations.AlterField(
            model_name='section',
            name='availability',
            field=models.JSONField(default=class_scheduler_app.models.default_availability),
        ),
    ]
