# Generated by Django 5.2.8 on 2025-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0011_remove_subject_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='availability_choice',
            field=models.TextField(choices=[('Unavailable', 'Unavailable'), ('Available Morning Weekly', 'Available Morning Weekly'), ('Available Afternoon Weekly', 'Available Afternoon Weekly'), ('Available Whole Day Weekly', 'Available Whole Day Weekly')], default='Unavailable'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.JSONField(default=list),
        ),
    ]
