# Generated by Django 5.2.8 on 2025-11-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduler_app', '0012_teacher_availability_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_scheduler_app.teacher')),
            ],
        ),
    ]
