# Generated by Django 5.2.2 on 2025-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_scheduler_app", "0013_alter_teacher_availability_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="max_weekly_loads",
            field=models.IntegerField(default=30),
        ),
    ]
